Add wayland-cursor bindings
ifreund/zig-wayland pull request #11
Opened 2020-12-04 01:57 UTC by Leon-Plickat

As discussed on IRC.

I am not sure if what I did here is right, I am not too familiar with zig yet.

I'll leave this as a draft until I have a chance to try it out.

2020-12-04 10:00 UTC, ifreund requested changes
Thanks for working on this!

2020-12-05 17:52 UTC, ifreund reviewed
Last review comments then this is good to go

2020-12-05 17:52 UTC, ifreund commented on src/wayland_client_core.zig
> +    name: ?[*:0]u8,
libwayland deferences this without checking in `wl_cursor_theme_get_cursor()`
```suggestion
    name: [*:0]u8,
```

2020-12-05 17:52 UTC, ifreund commented on src/wayland_client_core.zig
> +    extern fn wl_cursor_theme_load(name: ?[*:0]const u8, size: c_int, shm: *client.wl.Shm) ?*CursorTheme;
Let's make this return an `error.LoadThemeFailed` but keep `getCursor()` returning an optional.

2020-12-05 17:59 UTC, Leon-Plickat commented
All done.

2020-12-05 18:00 UTC, ifreund approved these changes
LGTM, thanks!

2020-12-05 18:00 UTC, merged