scanner: clean up
ifreund/zig-wayland pull request #21
Opened 2021-05-14 09:07 UTC by novakne

use std.fmt to define custom Formatter for title/camel case

replace `printIdentifier()` and `isValidIdentifier()` with std.zig.fmtId

add zig-out/ to .gitignore

**Todo:**

- [ ] Fix `trimPrefix()` with title/camel case, currently I didn't find a good solution to handle this and it cause the build to failed
- [ ] Use the original variable name instead of title_case, I'm still not sure how to do it
- [ ] Maybe more thing?

2021-05-15 07:59 UTC, novakne commented
I thought about doing something like this, but it add a lot of functions and still doesn't works perfectly
https://zigbin.io/520e43

2021-05-17 11:05 UTC, novakne commented
I made some errors in the commit message, I'll fix this after everything is done

2021-05-17 13:53 UTC, novakne commented
@ifreund Unless you want me to change some things, I'm done with what I wanted to do I think

2021-05-18 05:33 UTC, novakne commented
rebase and squash commits

2021-05-21 08:07 UTC, novakne commented
Just removed a forgotten useless 'prefix' in enum Case

2021-05-21 10:48 UTC, ifreund requested changes
Overall this is looking like a very nice improvement, thanks.

What would you think about using longer names for the format specifiers? For example `type`/`@"type"` instead of `tc`, `namespace` instead of `ns`, `interface` instead of `in`, etc.

2021-05-21 10:48 UTC, ifreund commented on src/scanner.zig
> +        , .{ .in = fmtId(interface.name) });
this shouldn't use `fmtId()` as the produced code would be invalid if interface.name was an identifier in the current scope:
```zig
extern const @"foobar"_interface
```

2021-05-21 10:48 UTC, ifreund commented on src/scanner.zig
> +                            , .{ .ct = fmtId(c_type), .an = fmtId(arg.name) });
```suggestion
                            , .{ .ct = c_type, .an = fmtId(arg.name) });
```

2021-05-21 11:25 UTC, novakne commented
> What would you think about using longer names for the format specifiers? For example `type`/`@"type"` instead of `tc`, `namespace` instead of `ns`, `interface` instead of `in`, etc.

I could change it yeah, I hesitated to use longer names, it would be more clear but also more verbose, we could have some really long lines, so would it make it really more clear I'm not sure. I guess it depends on each one preference

2021-05-21 12:08 UTC, novakne commented
hmm also `@"type"` gonna messed up a lot of things

for exemple 
``` zig
// works here
        try writer.print(
            \\pub const {[@"type"]} = opaque {{
            \\ pub const getInterface = common.{[namespace]}.{[interface]}.getInterface;
        , .{
            .@"type" = titleCaseTrim(interface.name),

// but not here:
        for (interface.enums.items) |e| {
            try writer.print("pub const {[@"type"]} = common.{[namespace]}.{[interface]}.{[@"type"]};\n", .{
                .@"type" = titleCase(e.name),

```
It could be a bit messy

2021-05-21 12:41 UTC, ifreund commented
> hmm also `@"type"` gonna messed up a lot of things

using the `@""` syntax inside the format specifier isn't needed and probably won't work.

```zig
            try writer.print("pub const {[type]} = common.{[namespace]}.{[interface]}.{[@"type"]};\n", .{
                .@"type" = titleCase(e.name),
```

2021-05-21 13:31 UTC, novakne commented
Let me now if that what you want and if it looks better with long names for you

2021-05-21 14:15 UTC, ifreund reviewed
I like the longer names, they make the format strings much more readable IMO

2021-05-21 14:28 UTC, novakne commented on src/scanner.zig
> +                    .function1 = camelCase(func[1]),
how about `function_name` or just `function` for `function0` then?

2021-05-21 15:08 UTC, ifreund commented on src/scanner.zig
> +                    .function1 = camelCase(func[1]),
> how about `function_name` or just `function` for `function0` then?

just function sounds good to me!

2021-05-21 15:17 UTC, novakne commented
Well it should all be good now, want me to squash all of this in one commit?

2021-05-23 11:06 UTC, merged

2021-05-23 11:06 UTC, ifreund commented
Thanks! I just went ahead and squashed it myself.